export const CHALLENGE_LIST_SUCCESS = "CHALLENGE_LIST_SUCCESS"
export const NAVIGATE_TO_CHALLENGE_LIST = "NAVIGATE_TO_CHALLENGE_LIST"
export const NAVIGATE_TO_CHALLENGE_DETAILS = "NAVIGATE_TO_CHALLENGE_DETAILS"